apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-openshift-plus
placementBindingDefaults:
  name: binding-policy-openshift-plus-hub
policyDefaults:
  categories:
    - CM Configuration Management
  controls: 
    - CM-2 Baseline Configuration
  namespace: policies
  policySets:
    - openshift-plus-hub
  severity: medium
  standards:
    - NIST SP 800-53
policies:
# ACS Policies - end
# Observability Policy - start
- name: policy-ocm-observability
  consolidateManifests: false
  categories:
    - CA Assessment Authorization and Monitoring
  controls: 
    - CA-7 Continuous Monitoring
  dependencies:
    - name: policy-odf
  manifests:
    - path: input-acm-observability/
  remediationAction: enforce  
# Observability Policy - end
# ODF Policies - start
- name: policy-odf
  categories:
    - SI System and Information Integrity
  controls: 
    - SI-7 Software Firmware and Information Integrity
  manifests:
    - path: input-odf/policy-odf.yaml
  remediationAction: enforce  
- name: policy-odf-status
  categories:
    - SI System and Information Integrity
  controls: 
    - SI-7 Software Firmware and Information Integrity
  dependencies:
    - name: policy-odf
  manifests:
    - path: input-odf/policy-odf-status.yaml
  remediationAction: inform
# ODF Policies - end
  policySets:
    - openshift-plus-clusters
    - openshift-plus-hub
# Compliance Operator Policies - end
policySets:
  - description: The OpenShift Platform Plus policy set applies several policies
      that will install the OpenShift Platform Plus products using best practices
      that allow them to work well together. This policy set is focused on 
      the components that install to the Advanced Cluster Management hub.
    name: openshift-plus-hub
    placement:
      placementPath: input/hub-placement.yaml
  - description: The OpenShift Platform Plus policy set applies several policies
      that install the OpenShift Platform Plus products using best practices
      that allow them to work well together. This policy set is focused on 
      the components that install to every managed cluster.
    name: openshift-plus-clusters
    placement:
      placementPath: input/clusters-placement.yaml
